import { ProposalSnapshot, CompanyInfo } from './types';

export const mockSnapshot: ProposalSnapshot = {
  client: {
    domain: 'example-travel.co.il',
    companyName: 'טיסות ישראל',
    contactName: 'דני כהן',
    industry: 'תיירות ונסיעות',
    proposalDate: '2024-12-23',
  },
  kpis: [
    {
      label: 'תנועה אורגנית חודשית',
      value: 'ממתין לגישות',
      isPlaceholder: true,
    },
    {
      label: 'מילות מפתח ממוקמות',
      value: 47,
      change: -12,
      trend: 'down',
    },
    {
      label: 'דירוג ממוצע',
      value: 34.5,
      change: 8,
      trend: 'down',
    },
    {
      label: 'הזדמנויות שזיהינו',
      value: 156,
      trend: 'up',
    },
  ],
  keywords: [
    {
      keyword: 'טיסות לדובאי',
      searchVolumeIL: 14000,
      searchVolumeGlobal: 1200000,
      currentPosition: null,
      intent: 'transactional',
      isMoneyKeyword: true,
    },
    {
      keyword: 'flydubai',
      searchVolumeIL: 26000,
      searchVolumeGlobal: 4500000,
      currentPosition: 45,
      intent: 'navigational',
      isMoneyKeyword: true,
    },
    {
      keyword: 'emirates',
      searchVolumeIL: 13000,
      searchVolumeGlobal: 8200000,
      currentPosition: 78,
      intent: 'navigational',
      isMoneyKeyword: true,
    },
    {
      keyword: 'טיסות לדובאי מחירים',
      searchVolumeIL: 8500,
      searchVolumeGlobal: 8500,
      currentPosition: 12,
      intent: 'transactional',
      isMoneyKeyword: true,
    },
    {
      keyword: 'חופשה בתאילנד',
      searchVolumeIL: 6200,
      searchVolumeGlobal: 12000,
      currentPosition: null,
      intent: 'commercial',
    },
    {
      keyword: 'טיסות זולות לאירופה',
      searchVolumeIL: 4800,
      searchVolumeGlobal: 180000,
      currentPosition: 23,
      intent: 'transactional',
      isMoneyKeyword: true,
    },
    {
      keyword: 'מלונות בפריז',
      searchVolumeIL: 3900,
      searchVolumeGlobal: 450000,
      currentPosition: null,
      intent: 'commercial',
    },
    {
      keyword: 'השכרת רכב בברצלונה',
      searchVolumeIL: 2100,
      searchVolumeGlobal: 45000,
      currentPosition: 34,
      intent: 'transactional',
    },
    {
      keyword: 'ביטוח נסיעות לחול',
      searchVolumeIL: 5600,
      searchVolumeGlobal: 5600,
      currentPosition: 8,
      intent: 'commercial',
    },
  ],
  findings: [
    {
      id: '1',
      title: 'אין תוכן FAQ מותאם ל-AI',
      description: 'האתר חסר דפי שאלות ותשובות שמבנים את התוכן בצורה ש-ChatGPT ו-Gemini יכולים לקרוא ולצטט.',
      severity: 'high',
      category: 'ai',
    },
    {
      id: '2',
      title: 'חסר Schema Markup',
      description: 'אין סכמה מובנית לעסק, מוצרים או FAQ - מה שמונע הופעה בתוצאות עשירות ובתשובות AI.',
      severity: 'high',
      category: 'technical',
    },
    {
      id: '3',
      title: 'הזדמנות לקידום ב-ChatGPT',
      description: 'המתחרים כבר מופיעים בתשובות AI לשאילתות תיירות. יש חלון הזדמנויות להיכנס לתחום.',
      severity: 'medium',
      category: 'ai',
    },
    {
      id: '4',
      title: 'מהירות טעינה איטית במובייל',
      description: 'ציון Core Web Vitals נמוך - LCP של 4.2 שניות. משפיע על דירוג ושיעור המרה.',
      severity: 'high',
      category: 'technical',
    },
    {
      id: '5',
      title: 'פוטנציאל קישורים חיצוניים',
      description: 'זיהינו 23 הזדמנויות לקישורים מאתרי תיירות ומגזינים ישראליים.',
      severity: 'medium',
      category: 'links',
    },
  ],
  recommendedServices: [
    {
      id: 'seo',
      name: 'SEO אורגני',
      nameEn: 'Organic SEO',
      description: 'קידום אורגני מקיף להגדלת התנועה והמכירות מגוגל',
      includes: [
        'מחקר מילות מפתח מעמיק',
        'אופטימיזציית On-Page מלאה',
        'בניית קישורים איכותיים',
        'תוכן אופטימלי ל-SEO',
        'דוחות ביצועים חודשיים',
      ],
      whyItMatters: 'תנועה אורגנית היא המקור הכי משתלם ללידים איכותיים לטווח ארוך.',
      icon: 'Search',
      isRecommended: true,
    },
    {
      id: 'geo',
      name: 'GEO - קידום ב-AI',
      nameEn: 'Generative Engine Optimization',
      description: 'אופטימיזציה להופעה בתשובות ChatGPT, Gemini ו-Grok',
      includes: [
        'אופטימיזציה למנועי AI',
        'בניית תוכן FAQ מובנה',
        'Schema Markup מתקדם',
        'מעקב ציטוטים ב-AI',
        'אסטרטגיית E-E-A-T',
      ],
      whyItMatters: '40% מהחיפושים עוברים ל-AI. מי שלא שם - מפסיד לקוחות למתחרים.',
      icon: 'Bot',
      isRecommended: true,
    },
    {
      id: 'content',
      name: 'תוכן ומאמרים',
      nameEn: 'Content Marketing',
      description: 'יצירת תוכן איכותי שמביא תנועה וממיר',
      includes: [
        'מאמרי FAQ מפורטים',
        'מדריכים ומאמרי How-To',
        'תוכן לבלוג עסקי',
        'דפי נחיתה אופטימליים',
        'עדכון תוכן קיים',
      ],
      whyItMatters: 'תוכן איכותי בונה סמכות, מביא תנועה ומשפר המרות.',
      icon: 'FileText',
    },
    {
      id: 'gbp',
      name: 'Google Business Profile',
      nameEn: 'Google Business Profile',
      description: 'ניהול ואופטימיזציה של הפרופיל העסקי בגוגל',
      includes: [
        'אופטימיזציית פרופיל מלאה',
        'ניהול ביקורות',
        'פוסטים שבועיים',
        'תמונות ומדיה',
        'מענה לשאלות',
      ],
      whyItMatters: 'חיוני לעסקים מקומיים - משפר נראות במפות ובחיפוש מקומי.',
      icon: 'MapPin',
    },
    {
      id: 'automation',
      name: 'אוטומציות ו-CRM',
      nameEn: 'Automation & CRM',
      description: 'אוטומציה של תהליכי מכירות ושירות לקוחות',
      includes: [
        'הטמעת מערכת CRM',
        'אוטומציות דוא"ל',
        'ניהול לידים אוטומטי',
        'דשבורדים ודוחות',
        'אינטגרציות עם מערכות',
      ],
      whyItMatters: 'חוסך זמן, מונע נפילת לידים ומשפר את חווית הלקוח.',
      icon: 'Zap',
    },
  ],
  accessItems: [
    {
      id: 'ga4',
      name: 'Google Analytics 4',
      nameEn: 'GA4',
      description: 'גישת צפייה לנתוני התנועה והמרות',
      status: 'missing',
      ctaLabel: 'הענק גישה',
      ctaUrl: 'https://analytics.google.com',
    },
    {
      id: 'gsc',
      name: 'Google Search Console',
      nameEn: 'GSC',
      description: 'גישה לנתוני חיפוש ואינדוקס',
      status: 'missing',
      ctaLabel: 'הענק גישה',
      ctaUrl: 'https://search.google.com/search-console',
    },
    {
      id: 'gtm',
      name: 'Google Tag Manager',
      nameEn: 'GTM',
      description: 'גישה לניהול תגיות ומעקב',
      status: 'requested',
      ctaLabel: 'בהמתנה',
    },
    {
      id: 'cms',
      name: 'גישת עריכה ל-CMS',
      nameEn: 'CMS Access',
      description: 'גישה למערכת ניהול התוכן לביצוע שינויים',
      status: 'missing',
      ctaLabel: 'צור קשר',
    },
    {
      id: 'ads',
      name: 'Google Ads',
      nameEn: 'Google Ads',
      description: 'גישת צפייה לקמפיינים ממומנים (אם רלוונטי)',
      status: 'received',
      ctaLabel: 'התקבל ✓',
    },
    {
      id: 'gbp',
      name: 'Google Business Profile',
      nameEn: 'GBP',
      description: 'גישת ניהול לפרופיל העסקי',
      status: 'missing',
      ctaLabel: 'הענק גישה',
      ctaUrl: 'https://business.google.com',
    },
    {
      id: 'merchant',
      name: 'Google Merchant Center',
      nameEn: 'Merchant Center',
      description: 'גישה לניהול פיד המוצרים (לחנויות)',
      status: 'missing',
      ctaLabel: 'הענק גישה',
      ctaUrl: 'https://merchants.google.com',
    },
  ],
  opportunitySummary: 'זיהינו פוטנציאל משמעותי להגדלת התנועה האורגנית ב-150%+ תוך 6-12 חודשים. הפערים העיקריים הם בתוכן מותאם AI, Schema markup, ובניית קישורים. עם הגישות הנדרשות, נוכל לבנות תוכנית עבודה מפורטת.',
};

export const companyInfo: CompanyInfo = {
  name: 'JustInTime Marketing',
  tagline: 'שיווק דיגיטלי שמביא תוצאות',
  description: `אנחנו צוות של מומחי SEO, תוכן ואוטומציה עם ניסיון של למעלה מ-20 שנים בשוק הישראלי והבינלאומי. 
  
התמחותנו היא בהבאת תוצאות מדידות - לא רק דירוגים, אלא תנועה, לידים ומכירות. אנחנו עובדים עם עסקים מכל הגדלים, מסטארטאפים ועד חברות ציבוריות.

הגישה שלנו משלבת SEO קלאסי עם הטכנולוגיות החדשות ביותר - כולל אופטימיזציה למנועי AI כמו ChatGPT ו-Gemini, ואוטומציות חכמות לייעול תהליכים עסקיים.`,
  services: [
    'קידום אורגני (SEO)',
    'קידום ב-AI (GEO)',
    'שיווק תוכן',
    'בניית קישורים',
    'Google Business Profile',
    'אוטומציות עסקיות',
  ],
  processSteps: [
    {
      step: 1,
      title: 'אבחון ומחקר',
      description: 'ניתוח מעמיק של האתר, המתחרים ושוק מילות המפתח. מזהים הזדמנויות ופערים.',
    },
    {
      step: 2,
      title: 'אסטרטגיה ותוכנית',
      description: 'בונים תוכנית עבודה מפורטת עם יעדים, לוחות זמנים וKPIs.',
    },
    {
      step: 3,
      title: 'יישום ואופטימיזציה',
      description: 'מבצעים את העבודה - תוכן, טכני, קישורים. הכל מתועד ושקוף.',
    },
    {
      step: 4,
      title: 'מעקב ושיפור',
      description: 'דוחות חודשיים, מעקב תוצאות והתאמת האסטרטגיה לפי הנתונים.',
    },
  ],
  faqs: [
    {
      question: 'מה זה SEO וקידום אורגני?',
      answer: 'SEO (Search Engine Optimization) הוא תהליך של אופטימיזציה של אתר אינטרנט כדי שיופיע בתוצאות החיפוש של גוגל. זה כולל אופטימיזציה טכנית, תוכן איכותי ובניית קישורים. התוצאה היא תנועה חינמית ואיכותית לאתר.',
    },
    {
      question: 'מה זה GEO - קידום ב-AI?',
      answer: 'GEO (Generative Engine Optimization) הוא תחום חדש שמתמקד בהופעה בתשובות של מנועי AI כמו ChatGPT, Gemini ו-Grok. עם עליית השימוש ב-AI לחיפוש מידע, חשוב להבטיח שהעסק שלך מופיע בתשובות שהם מייצרים.',
    },
    {
      question: 'מה זה Schema Markup ולמה זה חשוב?',
      answer: 'Schema Markup הוא קוד מיוחד שמוסיפים לאתר שעוזר למנועי חיפוש להבין טוב יותר את התוכן. זה מאפשר הופעה בתוצאות עשירות (כוכבי דירוג, מחירים, FAQ) וגם עוזר למנועי AI לזהות ולצטט את התוכן שלך.',
    },
    {
      question: 'איך אוטומציות יכולות לעזור לעסק שלי?',
      answer: 'אוטומציות עסקיות חוסכות זמן יקר ומייעלות תהליכים. למשל: ניהול לידים אוטומטי, תזכורות ללקוחות, דוחות אוטומטיים, אינטגרציה בין מערכות, וצ\'אטבוטים חכמים. זה מאפשר לצוות להתמקד במה שחשוב באמת במקום במשימות חוזרות.',
    },
    {
      question: 'מה ההבדל בין קידום אורגני לקידום ממומן?',
      answer: 'קידום אורגני (SEO) מתמקד בהופעה בתוצאות החיפוש הטבעיות ללא תשלום לגוגל על כל קליק. קידום ממומן (PPC) הוא פרסום בתשלום שבו משלמים על כל קליק. SEO הוא השקעה לטווח ארוך שממשיכה להניב תוצאות, בעוד PPC עוצר ברגע שמפסיקים לשלם.',
    },
    {
      question: 'מה זה Core Web Vitals?',
      answer: 'Core Web Vitals הם מדדים של גוגל שמודדים את חווית המשתמש באתר: מהירות טעינה (LCP), יציבות ויזואלית (CLS), ואינטראקטיביות (INP). אתרים עם ציונים טובים מקבלים יתרון בדירוג ומשפרים את שיעור ההמרה.',
    },
  ],
  contact: {
    email: 'info@justintime.co.il',
    phone: '050-787-7165',
    website: 'justintime.co.il',
  },
};


